import * as fs from "node:fs";
import * as path from "node:path";

const MCP_SERVER_KEY = "prism";

/**
 * Cursor / VS Code MCP auto-registration (file-based; feature-detect, no version sniffing).
 */
export async function registerMcp(
  workspaceRoot: string,
  prismPath: string,
  enable: boolean,
): Promise<string> {
  const cursorDir = path.join(workspaceRoot, ".cursor");
  const cursorMcp = path.join(cursorDir, "mcp.json");
  const vscodeMcp = path.join(workspaceRoot, ".vscode", "mcp.json");

  const target = fs.existsSync(cursorDir) ? cursorMcp : vscodeMcp;

  if (!enable) {
    if (fs.existsSync(target)) {
      const raw = JSON.parse(fs.readFileSync(target, "utf8")) as {
        mcpServers?: Record<string, unknown>;
      };
      if (raw.mcpServers?.[MCP_SERVER_KEY]) {
        delete raw.mcpServers[MCP_SERVER_KEY];
        fs.writeFileSync(target, JSON.stringify(raw, null, 2) + "\n");
      }
    }
    return `Disabled MCP registration (${target})`;
  }

  const dir = path.dirname(target);
  fs.mkdirSync(dir, { recursive: true });
  let raw: { mcpServers?: Record<string, unknown> } = { mcpServers: {} };
  if (fs.existsSync(target)) {
    try {
      raw = JSON.parse(fs.readFileSync(target, "utf8"));
    } catch {
      raw = { mcpServers: {} };
    }
  }
  raw.mcpServers = raw.mcpServers ?? {};
  raw.mcpServers[MCP_SERVER_KEY] = {
    command: prismPath,
    args: ["mcp", workspaceRoot],
  };
  fs.writeFileSync(target, JSON.stringify(raw, null, 2) + "\n");
  return `Registered Prism MCP at ${target} (toggle via Prism: Disable Cursor MCP Registration)`;
}

const AGENTS_TEMPLATE = `# AGENTS.md — Prism guidance (generated)

> Regenerated by the Prism extension from docs/architecture/AGENT-USAGE.md.
> Prefer \`compile_context\` before explore loops.

## Primary path

1. Call **compile_context** (MCP) or **Prism: Compile Context** (IDE) with a question + anchors.
2. Answer from Evidence Pack citations; inspect gaps / EXPLAIN drops if unsure.
3. Use micro-tools (\`resolve_symbol\`, \`neighbors\`, \`impact\`, \`repo_map\`) only for targeted follow-ups.

## Refusals → next action

| Code | Do this |
|---|---|
| SCOPE_UNRESOLVED | Pick a symbol / path / stack frame (IDE: Prism: Pick Anchor) |
| BUDGET_EXCEEDED | Raise budget_tokens or narrow anchors |
| INDEX_UNAVAILABLE | Prism: Build Index |
| PRECISION_REQUIRED | Import PreciseIndex / SCIP, or continue with labeled heuristic |
| VIEW_TOO_LARGE | Narrow seeds / anchors for the graph view |

## Anti-patterns

- Do not open dozens of files via grep/read when compile_context can answer.
- Do not claim rename safety from unlabeled impact — use require_precise / rename-dry-run.
`;

export function generateAgentsMd(workspaceRoot: string): string {
  const out = path.join(workspaceRoot, "AGENTS.md");
  const banner = `<!-- prism:generated from AGENT-USAGE — regenerate via Prism: Generate AGENTS.md -->\n`;
  fs.writeFileSync(out, banner + AGENTS_TEMPLATE);
  const rulesDir = path.join(workspaceRoot, ".cursor", "rules");
  fs.mkdirSync(rulesDir, { recursive: true });
  fs.writeFileSync(
    path.join(rulesDir, "prism-compile-first.mdc"),
    `---
description: Prefer Prism compile_context before explore loops
globs:
alwaysApply: true
---

${AGENTS_TEMPLATE}
`,
  );
  return out;
}

/** Redact pack text for clipboard — strip long bodies, keep citations + meta. */
export function redactPackForLlm(pack: unknown): string {
  const p = pack as {
    meta?: unknown;
    citations?: unknown;
    fragments?: Array<{
      id: string;
      kind: string;
      layer: string;
      text: string;
      why_included?: string;
    }>;
    gaps?: unknown;
  };
  const frags = (p.fragments ?? []).map((f) => ({
    id: f.id,
    kind: f.kind,
    layer: f.layer,
    why_included: f.why_included,
    text:
      f.text.length > 800
        ? f.text.slice(0, 800) + "\n…[redacted for length]"
        : f.text,
  }));
  return JSON.stringify(
    { meta: p.meta, citations: p.citations, fragments: frags, gaps: p.gaps },
    null,
    2,
  );
}
